[build-system]
requires = ["hatchling>=1.18.0"]
build-backend = "hatchling.build"

[project]
name = "chaskiwasi"  # <-- Cambiado al nombre real de tu librería
version = "0.2.2"
description = "Sistema de consulta semántica para fuentes jurídicas."
readme = "README.md"
authors = [
    { name = "Luis Maurtua", email = "luis.maurtua@ejemplo.com" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.10"
dependencies = [
    "pymupdf>=1.24.0,<2.0.0",
    "opencv-python>=4.8.0,<5.0.0",
    "pytesseract>=0.3.10,<4.1.3",
    "deskew>=1.5.0,<2.0.0",
    "google-genai>=2.0.0,<3.0.0",     # Alineado con la evolución actual del SDK de Gemini
    "python-dotenv>=1.0.0,<2.0.0",
    "pydantic>=2.0.0,<3.0.0",
    "docling>=2.0.0,<3.0.0",
    "rapidocr-onnxruntime>=1.3.0,<2.0.0"
]

[project.urls]
Homepage = "https://github.com/Maorda/chaskywasi"
Issues = "https://github.com/Maorda/chaskywasi/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/chaskiwasi"]

[project.scripts]
chaskiwasi = "chaskiwasi.cli:app"